apps/notificacoes/urls.py
from django.urls import path
from . import views

app_name = "notificacoes"

urlpatterns = [
    path('', views.notificacoes, name="notificacoes"),
    path('detalhe_notificacao/<int:id>/', views.detalhe_notificacao, name="detalhe_notificacao"),
    path('nova_notificacao/', views.nova_notificacao, name="nova_notificacao"),
]

siraf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('perfil/', include('apps.perfil.urls')),
    path('notificacoes/', include('apps.notificacoes.urls')),
    path('juridico/', include('apps.juridico.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name="login"),
    path('accounts/', include('django.contrib.auth.urls'), name="logout"),
    path('admin/', admin.site.urls),
]

apps/notificacoes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count, Avg


class Notificacoes(models.Model):
    ALERT_CHOICES = (
        ("d", "urgente"),
        ("s", "normal"),
        ("w", "atenção")
    )
    alert = models.CharField(
        max_length=1, choices=ALERT_CHOICES, blank=False, null=False)
    title = models.CharField(max_length=50, null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    date = models.DateField(auto_now=False, auto_now_add=True)
    icon = models.CharField(max_length=50, null=True, blank=True)
    message_to = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True, related_name='message_to')
    message_from = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True, related_name='message_from')

    def listar_notificacoes(id):
        return Notificacoes.objects.filter(message_from=id)

    def detalhe_notificacao(id):
        return Notificacoes.objects.filter(id=id)

    def listar_notificacoes_menu(id):
        return Notificacoes.objects.filter(message_from=id).order_by('-pk')[:4]

    def qtd_notificacoes(id):
        return Notificacoes.objects.filter(message_from=id).aggregate(Count('id'))['id__count']

    def __str__(self):
        return self.title

apps/notificacoes/forms.py
from django.forms import ModelForm
from . models import Notificacoes


class NotificacoesForm(ModelForm):
    class Meta:
        model = Notificacoes
        fields = ['alert', 'title', 'text', 'icon', 'message_to', 'message_from']

apps/notificacoes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from . models import Notificacoes
from .forms import NotificacoesForm


def notificacoes(request):
    notificacoes = Notificacoes.listar_notificacoes(request.user.id)
    notificacoes_menu = Notificacoes.listar_notificacoes_menu(request.user.id)
    qtd_notificacao = Notificacoes.qtd_notificacoes(request.user.id)
    return render(request, 'notificacoes/notificacoes.html', {
        'notificacoes': notificacoes,
        'notificacoes_menu': notificacoes_menu,
        'qtd_notificacao': qtd_notificacao
    })


def detalhe_notificacao(request, id):
    notificacoes = Notificacoes.listar_notificacoes(request.user.id)
    notificacoes_menu = Notificacoes.listar_notificacoes_menu(request.user.id)
    qtd_notificacao = Notificacoes.qtd_notificacoes(request.user.id)
    detalhe_notificacoes = Notificacoes.detalhe_notificacao(id)
    return render(request, 'notificacoes/detalhe_notificacoes.html', {
        'notificacoes': notificacoes,
        'notificacoes_menu': notificacoes_menu,
        'qtd_notificacao': qtd_notificacao,
        'detalhe_notificacoes': detalhe_notificacoes
    })


def nova_notificacao(request):
    qtd_notificacao = Notificacoes.qtd_notificacoes(request.user.id)
    notificacoes_menu = Notificacoes.listar_notificacoes_menu(request.user.id)
    form = NotificacoesForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/notificacoes/")
    return render(request, 'notificacoes/notificacoes_form.html', 
    {'form': form, 
    'qtd_notificacao': qtd_notificacao,
    'notificacoes_menu': notificacoes_menu,
    })

apps/notificacoes/templates/notificacoes/_notificacoes.html
<h1>notificacoes.html</h1>

apps/notificacoes/templates/notificacoes/detalhe_notificacoes.html
{% extends 'plataforma_base.html' %}



{% block title %}
Notificações
{% endblock title %}


{% block content %}
<div id="content" class="app-content p-0">
    <!-- BEGIN mailbox -->
    <div class="mailbox">
        <!-- BEGIN mailbox-toolbar -->
        <div class="mailbox-toolbar">

            <div class="mailbox-toolbar-item"><a href="{% url 'notificacoes:nova_notificacao' %}"
                    class="mailbox-toolbar-link text-primary bg-blue-transparent-1">Nova Mensagem <i
                        class="fa fa-pen fs-12px ms-1"></i></a></div>
        </div>
        <!-- END mailbox-toolbar -->
        <!-- BEGIN mailbox-body -->
        <div class="mailbox-body">

            <!-- BEGIN mailbox-sidebar -->



            <div class="mailbox-sidebar d-none d-lg-block">
                <div data-scrollbar="true" data-height="100%" data-skip-mobile="true">
                    <div class="mailbox-list">
                        {% for notificacao in notificacoes %}
                        <div class="mailbox-list-item unread has-attachment">
                            <div class="mailbox-message">
                                <a href="{% url 'notificacoes:detalhe_notificacao' notificacao.id %}"
                                    class="mailbox-list-item-link">
                                    <div class="mailbox-sender">
                                        <span class="mailbox-sender-name">{{ notificacao.title }}</span>
                                        <span class="mailbox-time">{{ notificacao.date }}</span>
                                    </div>
                                    <div class="mailbox-title">{{ notificacao.user_notificacoes }}</div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>



            <!-- END mailbox-sidebar -->
            <!-- BEGIN mailbox-content -->


            <div class="mailbox-content">
                <!-- BEGIN scrollbar -->
                <div data-scrollbar="true" data-height="100%" data-skip-mobile="true">
                    <!-- BEGIN mailbox-detail -->
                    {% for detalhe_notificacao in detalhe_notificacoes %}
                    <div class="mailbox-detail">

                        <!-- BEGIN mail-detail-header -->
                        <div class="mailbox-detail-header">
                            <div class="d-flex">
                                <a href="#">
                                    <img src="assets/img/user/user-1.jpg" alt="" width="40" class="rounded-circle" />
                                </a>
                                <div class="flex-fill ms-3">
                                    <div class="d-flex align-items-center">
                                        <div class="flex-fill">
                                            <div class="font-weight-600">{{ detalhe_notificacao.message_to }}</div>
                                            <div class="fs-13px">
                                                <span class="me-1">para</span> <a href="#"
                                                    class="text-decoration-none">{{ request.user }}</a>
                                            </div>
                                        </div>
                                        <div class="fs-12px text-muted text-end">{{ detalhe_notificacao.date }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- END mailbox-detail-header -->
                        <!-- BEGIN mailbox-detail-content -->
                        <div class="mailbox-detail-content">
                            <h4 class="mb-3">{{ detalhe_notificacao.user_notificacoes }}</h4>

                            <!-- BEGIN mailbox-detail-body -->
                            <div class="mailbox-detail-body">
                                {{ detalhe_notificacao.text }}
                            </div>
                            <!-- END mailbox-detail-body -->
                        </div>
                        <!-- END mailbox-detail-content -->

                    </div>
                    <!-- END mailbox-detail -->
                    {% endfor %}
                </div>
                <!-- END scrollbar -->
            </div>




            <!-- END mailbox-content -->
        </div>
        <!-- END mailbox-body -->
    </div>
    <!-- END mailbox -->
</div>
{% endblock content %}

apps/notificacoes/templates/notificacoes/notificacoes.html
{% extends 'plataforma_base.html' %}
{% load static %}


{% block title %}
Notificações
{% endblock title %}


{% block content %}
<div id="content" class="app-content p-0">
    <!-- BEGIN mailbox -->
    <div class="mailbox">
        <!-- BEGIN mailbox-toolbar -->
        <div class="mailbox-toolbar">

            <div class="mailbox-toolbar-item"><a href="{% url 'notificacoes:nova_notificacao' %}"
                    class="mailbox-toolbar-link text-primary bg-blue-transparent-1">Nova Mensagem <i
                        class="fa fa-pen fs-12px ms-1"></i></a></div>
        </div>
        <!-- END mailbox-toolbar -->
        <!-- BEGIN mailbox-body -->
        <div class="mailbox-body">

            <!-- BEGIN mailbox-sidebar -->



            <div class="mailbox-sidebar">
                <div data-scrollbar="true" data-height="100%" data-skip-mobile="true">
                    <div class="mailbox-list">
                        {% for notificacao in notificacoes %}
                        <div class="mailbox-list-item unread has-attachment">
                            <div class="mailbox-message">
                                <a href="{% url 'notificacoes:detalhe_notificacao' notificacao.id %}"
                                    class="mailbox-list-item-link">
                                    <div class="mailbox-sender">
                                        <span class="mailbox-sender-name">{{ notificacao.title }}</span>
                                        <span class="mailbox-time">{{ notificacao.date }}</span>
                                    </div>
                                    <div class="mailbox-title">{{ notificacao.user_notificacoes }}</div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>


            <!-- END mailbox-sidebar -->
            <!-- BEGIN mailbox-content -->
            <div class="mailbox-content d-none d-lg-block">
                <div data-scrollbar="true" data-height="100%" data-skip-mobile="true">
                    <div class="mailbox-empty-message">
                        <div class="mailbox-empty-message-img"><img
                                src="{% static 'plataforma/assets/img/page/email.svg' %}" alt="" /></div>
                        <div class="mailbox-empty-message-title">Nenhuma mensagem selecionada</div>
                    </div>
                </div>
            </div>
            <!-- END mailbox-content -->
        </div>
        <!-- END mailbox-body -->
    </div>
    <!-- END mailbox -->
</div>
{% endblock content %}

apps/notificacoes/templates/notificacoes/notificacoes_form.html
{% extends 'plataforma_base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
Notificações
{% endblock title %}


{% block content %}
<div id="content" class="app-content">
    <div class="container">
        <!-- BEGIN row -->
        <div class="row justify-content-center">
            <!-- BEGIN col-10 -->
            <div class="col-xl-10">
                <!-- BEGIN row -->
                <div class="row">
                    <!-- BEGIN col-9 -->
                    <div class="col-xl-9">
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">NOTIFICAÇÕES</a></li>
                            <li class="breadcrumb-item active">NOVA NOTIFICAÇÃO</li>
                        </ul>

                        <h1 class="page-header">
                            NOVA NOTIFICAÇÃO <small>Enviar mensagem</small>
                        </h1>

                        <hr class="mb-4" />

                        <!-- BEGIN #formControls -->
                        <div id="formControls" class="mb-5">
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="card">
                                    <div class="card-body pb-2">

                                        <div class="row">
                                            <div class="col-xl-12">
                                                <div class="form-group mb-3">
                                                    <label class="form-label" for="exampleFormControlInput1">De</label>
                                                    {{ form.message_to | add_class:"form-control form-select" }}
                                                </div>
                                                <div class="form-group mb-3">
                                                    <label class="form-label"
                                                        for="exampleFormControlTextarea1">Para</label>
                                                    {{ form.message_from | add_class:"form-control form-select" }}
                                                </div>


                                            </div>

                                        </div>

                                    </div>

                                </div>
                                <div class="card">
                                    <div class="card-body pb-2">

                                        <div class="row">
                                            <div class="col-xl-6">
                                                <div class="form-group mb-3">
                                                    <label class="form-label"
                                                        for="exampleFormControlInput1">Prioridade</label>
                                                    {{ form.alert | add_class:"form-control form-select" }}
                                                </div>
                                                <div class="form-group mb-3">
                                                    <label class="form-label"
                                                        for="exampleFormControlTextarea1">Titulo</label>
                                                    {{ form.title | add_class:"form-control" }}
                                                </div>


                                            </div>
                                            <div class="col-xl-6">
                                                <div class="form-group mb-3">
                                                    <label class="form-label"
                                                        for="exampleFormControlTextarea1">Texto</label>
                                                    {{ form.text | add_class:"form-control" }}
                                                </div>

                                            </div>
                                        </div>

                                    </div>
                                    <button type="submit" class="btn btn-primary">Enviar</button>
                            </form>
                        </div>

                    </div>
                    <!-- END #formControls -->
                </div>
                <!-- END col-9-->

            </div>
            <!-- END row -->
        </div>
        <!-- END col-10 -->
    </div>
    <!-- END row -->
</div>
</div>
{% endblock content %}