apps/juridico/urls.py
from django.urls import path
from . import views

app_name = "juridico"

urlpatterns = [
    path('', views.juridico, name="juridico"),
    path('dados_contrato/<int:id>/', views.dados_contrato, name="dados_contrato"),
    path('dados_aditivo_valor/<int:id_contract>/<int:id_aditivo>/', views.dados_aditivo_valor, name="dados_aditivo_valor"),
    path('dados_supressao/<int:id_contract>/<int:id_supressao>/', views.dados_supressao, name="dados_supressao"),
    path('item_contratos/<int:id>/', views.item_contratos, name="item_contratos"),
    path('listar_contratos/', views.listar_contratos, name="listar_contratos"),
    path('novo_contrato/', views.novo_contrato, name="novo_contrato"),
    path('novo_aditivo_prazo/<int:id>/', views.novo_aditivo_prazo, name="novo_aditivo_prazo"),
    path('novo_aditivo_valor/<int:id>/', views.novo_aditivo_valor, name="novo_aditivo_valor"),
    path('nova_supressao/<int:id>/', views.nova_supressao, name="nova_supressao"),
    path('configurar_itens_aditivo/<int:id>/<int:id_aditivo>/', views.configurar_itens_aditivo, name="configurar_itens_aditivo"),
    path('configurar_itens_supressao/<int:id>/<int:id_supressao>/', views.configurar_itens_supressao, name="configurar_itens_supressao"),
    path('editar_contrato/<int:id>/', views.editar_contrato, name="editar_contrato"),
    path('deletar_contrato/<int:id>/', views.deletar_contrato, name="deletar_contrato"),
    path('novo_item/', views.novo_item, name="novo_item"),
    path('novo_item_aditivo_valor/', views.novo_item_aditivo_valor, name="novo_item_aditivo_valor"),
    path('novo_item_supressao/', views.novo_item_supressao, name="novo_item_supressao"),
    path('excluir_item_aditivo_valor/<int:id_contract>/<int:id_aditivo>/<int:id_item>', views.excluir_item_aditivo_valor, name="excluir_item_aditivo_valor"),
    path('novo_item_session/<int:id>/', views.novo_item_session, name="novo_item_session"),
    path('editar_item/<int:id>/', views.editar_item, name="editar_item"),
    path('deletar_item/<int:id>/', views.deletar_item, name="deletar_item"),
    path('get_item/<int:id>/<int:id_aditivo>/<int:id_item>/', views.get_item, name="get_item"),
    path('get_item_supressao/<int:id>/<int:id_supressao>/<int:id_item>/', views.get_item_supressao, name="get_item_supressao"),
    path('novo_tipo/', views.novo_tipo, name="novo_tipo"),
    path('listar_tipos/', views.listar_tipos, name="listar_tipos"),
    path('editar_tipo/<int:id>/', views.editar_tipo, name="editar_tipo"),
    path('deletar_tipo/<int:id>/', views.deletar_tipo, name="deletar_tipo"),
    path('deletar_aditivo_praso/<int:id>/', views.deletar_aditivo_praso, name="deletar_aditivo_praso"),
    path('deletar_aditivo_valor/<int:id>/', views.deletar_aditivo_valor, name="deletar_aditivo_valor"),
     path('deletar_supressao/<int:id>/', views.deletar_supressao, name="deletar_supressao"),
    path('processos/<int:id_contract>/<company>/', views.processos, name="processos")
]

apps/notificacoes/urls.py
from django.urls import path
from . import views

app_name = "notificacoes"

urlpatterns = [
    path('', views.notificacoes, name="notificacoes"),
    path('detalhe_notificacao/<int:id>/', views.detalhe_notificacao, name="detalhe_notificacao"),
    path('nova_notificacao/', views.nova_notificacao, name="nova_notificacao"),
]

siraf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('perfil/', include('apps.perfil.urls')),
    path('notificacoes/', include('apps.notificacoes.urls')),
    path('juridico/', include('apps.juridico.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name="login"),
    path('accounts/', include('django.contrib.auth.urls'), name="logout"),
    path('admin/', admin.site.urls),
]

templates/partials/plataforma/_menu.html
{% load static %}
<form class="menu-search" method="POST" name="header_search_form">
    <div class="menu-search-icon"><i class="fa fa-search"></i></div>
    <div class="menu-search-input">
        <input type="text" class="form-control" placeholder="Pesquisar..." />
    </div>
</form>
<div class="menu-item dropdown">
    <a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
        <div class="menu-icon"><i class="fa fa-bell nav-icon"></i></div>
        <div class="menu-label">{{ qtd_notificacao }}</div>
    </a>
    <div class="dropdown-menu dropdown-menu-end dropdown-notification">
        <h6 class="dropdown-header text-gray-900 mb-1">Notificações</h6>

        {% for notificacao_menu in notificacoes_menu %}
        <a href="#" class="dropdown-notification-item">
            <div class="dropdown-notification-icon">


                {% if notificacao_menu.alert == 'd' %}
                <i class="fa fa-envelope fa-lg fa-fw text-danger"></i>
                {% elif notificacao_menu.alert == 's' %}
                <i class="fa fa-envelope fa-lg fa-fw text-success"></i>
                {% elif notificacao_menu.alert == 'w' %}
                <i class="fa fa-envelope fa-lg fa-fw text-warning"></i>
                {% endif %}



            </div>
            <div class="dropdown-notification-info">
                <div class="title">{{ notificacao_menu.text }}</div>
                <div class="time">{{ notificacao_menu.date }}</div>
            </div>
            <div class="dropdown-notification-arrow">
                <i class="fa fa-chevron-right"></i>
            </div>
        </a>
        {% endfor %}

        <div class="p-2 text-center mb-n1">
            <a href="{% url 'notificacoes:notificacoes' %}" class="text-gray-800 text-decoration-none">Todas</a>
        </div>
    </div>
</div>
<div class="menu-item dropdown">
    <a href="#" data-bs-toggle="dropdown" data-bs-display="static" class="menu-link">
        <!-- <div class="menu-img online">
            <img src="{% static 'plataforma/assets/img/user/user-10.jpg' %}" alt="" class="mw-100 mh-100 rounded-circle" />
        </div>-->
        <div class="menu-text">{{ user.perfil.email }}</div>
    </a>
    <div class="dropdown-menu dropdown-menu-end me-lg-3">
        <a class="dropdown-item d-flex align-items-center" href="#">Editar Perfil <i
                class="fa fa-user-circle fa-fw ms-auto text-gray-400 fs-16px"></i></a>

        <div class="dropdown-divider"></div>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">Sair <i
                class="fa fa-toggle-off fa-fw ms-auto text-gray-400 fs-16px"></i></a>
    </div>
</div>

templates/partials/plataforma/_message.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/plataforma/_sidebar.html
<div class="app-sidebar-content" data-scrollbar="true" data-height="100%">
    <!-- BEGIN menu -->
    <div class="menu">
        <div class="menu-header">Setores</div>
        <div class="menu-item">
            <a href="{% url 'juridico:juridico' %}" class="menu-link">
                <span class="menu-icon"><i class="fas fa-lg fa-fw me-2 fa-university"></i></span>
                <span class="menu-text">Juridico</span>
            </a>
        </div>
        <div class="menu-item">
            <a href="analytics.html" class="menu-link">
                <span class="menu-icon"><i class="far fa-lg fa-fw me-2 fa-money-bill-alt"></i></span>
                <span class="menu-text">Financeiro</span>
            </a>
        </div>
        <div class="menu-item">
            <a href="analytics.html" class="menu-link">
                <span class="menu-icon"><i class="fas fa-lg fa-fw me-2 fa-file-alt"></i></span>
                <span class="menu-text">Contrato</span>
            </a>
        </div>
        <div class="menu-item">
            <a href="analytics.html" class="menu-link">
                <span class="menu-icon"><i class="fas fa-lg fa-fw me-2 fa-users"></i></i></span>
                <span class="menu-text">Administrativo</span>
            </a>
        </div>
        <div class="menu-item">
            <a href="analytics.html" class="menu-link">
                <span class="menu-icon"><i class="fas fa-lg fa-fw me-2 fa-ticket-alt"></i></span>
                <span class="menu-text">Evento</span>
            </a>
        </div>
       








    </div>
    <!-- END menu -->
</div>

templates/partials/plataforma/_sidebar_juridico.html
	<!-- BEGIN scrollbar -->
    <div class="app-sidebar-content" data-scrollbar="true" data-height="100%">
        <!-- BEGIN menu -->
        <div class="menu">
            <div class="menu-header">Contrato</div>
            <div class="menu-item">
                <a href="{% url 'juridico:novo_contrato' %}" class="menu-link">
                    <span class="menu-icon"><i class="fa fa-file"></i></span>
                    <span class="menu-text">Novo Contrato</span>
                </a>
            </div>
            <div class="menu-item">
                <a href="{% url 'juridico:listar_contratos' %}" class="menu-link">
                    <span class="menu-icon"><i class="fa fa-list"></i></span>
                    <span class="menu-text">Listar Contratos</span>
                </a>
            </div>
            <div class="menu-item">
                <a href="{% url 'juridico:juridico' %}" class="menu-link">
                    <span class="menu-icon"><i class="fa fa-list"></i></span>
                    <span class="menu-text">Listar Item Contratos</span>
                </a>
            </div>
        
            <div class="menu-divider"></div>
            <div class="menu-header">Tipo</div>
            <div class="menu-item">
                <a href="{% url 'juridico:novo_tipo' %}" class="menu-link">
                    <span class="menu-icon"><i class="fa fa-file"></i></span>
                    <span class="menu-text">Tipo</span>
                </a>
            </div>
            <div class="menu-item">
                <a href="{% url 'juridico:listar_tipos' %}" class="menu-link">
                    <span class="menu-icon"><i class="fa fa-list"></i></span>
                    <span class="menu-text">Listar Tipos</span>
                </a>
            </div>
         
            
            <div class="p-3 px-4 mt-auto hide-on-minified">
                <a href="../../documentation/index.html" class="btn d-block btn-secondary font-weight-600 rounded-pill">
                    <i class="fa fa-code-branch me-1 ms-n1 opacity-5"></i> Tutorial
                </a>
            </div>
        </div>
        <!-- END menu -->
    </div>
    <!-- END scrollbar -->