apps/juridico/urls.py
from django.urls import path
from . import views

app_name = "juridico"

urlpatterns = [
    path('', views.juridico, name="juridico"),
    path('dados_contrato/<int:id>/', views.dados_contrato, name="dados_contrato"),
    path('dados_aditivo_valor/<int:id_contract>/<int:id_aditivo>/', views.dados_aditivo_valor, name="dados_aditivo_valor"),
    path('dados_supressao/<int:id_contract>/<int:id_supressao>/', views.dados_supressao, name="dados_supressao"),
    path('item_contratos/<int:id>/', views.item_contratos, name="item_contratos"),
    path('listar_contratos/', views.listar_contratos, name="listar_contratos"),
    path('novo_contrato/', views.novo_contrato, name="novo_contrato"),
    path('novo_aditivo_prazo/<int:id>/', views.novo_aditivo_prazo, name="novo_aditivo_prazo"),
    path('novo_aditivo_valor/<int:id>/', views.novo_aditivo_valor, name="novo_aditivo_valor"),
    path('nova_supressao/<int:id>/', views.nova_supressao, name="nova_supressao"),
    path('configurar_itens_aditivo/<int:id>/<int:id_aditivo>/', views.configurar_itens_aditivo, name="configurar_itens_aditivo"),
    path('configurar_itens_supressao/<int:id>/<int:id_supressao>/', views.configurar_itens_supressao, name="configurar_itens_supressao"),
    path('editar_contrato/<int:id>/', views.editar_contrato, name="editar_contrato"),
    path('deletar_contrato/<int:id>/', views.deletar_contrato, name="deletar_contrato"),
    path('novo_item/', views.novo_item, name="novo_item"),
    path('novo_item_aditivo_valor/', views.novo_item_aditivo_valor, name="novo_item_aditivo_valor"),
    path('novo_item_supressao/', views.novo_item_supressao, name="novo_item_supressao"),
    path('excluir_item_aditivo_valor/<int:id_contract>/<int:id_aditivo>/<int:id_item>', views.excluir_item_aditivo_valor, name="excluir_item_aditivo_valor"),
    path('novo_item_session/<int:id>/', views.novo_item_session, name="novo_item_session"),
    path('editar_item/<int:id>/', views.editar_item, name="editar_item"),
    path('deletar_item/<int:id>/', views.deletar_item, name="deletar_item"),
    path('get_item/<int:id>/<int:id_aditivo>/<int:id_item>/', views.get_item, name="get_item"),
    path('get_item_supressao/<int:id>/<int:id_supressao>/<int:id_item>/', views.get_item_supressao, name="get_item_supressao"),
    path('novo_tipo/', views.novo_tipo, name="novo_tipo"),
    path('listar_tipos/', views.listar_tipos, name="listar_tipos"),
    path('editar_tipo/<int:id>/', views.editar_tipo, name="editar_tipo"),
    path('deletar_tipo/<int:id>/', views.deletar_tipo, name="deletar_tipo"),
    path('deletar_aditivo_praso/<int:id>/', views.deletar_aditivo_praso, name="deletar_aditivo_praso"),
    path('deletar_aditivo_valor/<int:id>/', views.deletar_aditivo_valor, name="deletar_aditivo_valor"),
     path('deletar_supressao/<int:id>/', views.deletar_supressao, name="deletar_supressao"),
    path('processos/<int:id_contract>/<company>/', views.processos, name="processos")
]

siraf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('perfil/', include('apps.perfil.urls')),
    path('notificacoes/', include('apps.notificacoes.urls')),
    path('juridico/', include('apps.juridico.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name="login"),
    path('accounts/', include('django.contrib.auth.urls'), name="logout"),
    path('admin/', admin.site.urls),
]

apps/juridico/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum, Count
from django.db.models.expressions import F


class Tipo(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def listar_tipo():
        return Tipo.objects.all()

    def __str__(self):
        return self.name


class Contrato(models.Model):
    company = models.CharField(max_length=50)
    type = models.CharField(max_length=50, blank=True, null=True)
    date = models.DateField(auto_now=False, auto_now_add=True)
    number = models.CharField(max_length=50, blank=True, null=True)
    validity = models.IntegerField(blank=True, null=True)
    responsible = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True, related_name="responsible")
    signature_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    type_contrato = models.ForeignKey(
        Tipo, on_delete=models.PROTECT, null=True, blank=True)
    end_validity = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    official_diary = models.CharField(max_length=50, blank=True, null=True)

    def listar_contratos():
        return Contrato.objects.all()

    def contrato_id(id):
        return Contrato.objects.get(pk=id)

    def __str__(self):
        return self.company


class Item(models.Model):
    item = models.CharField(max_length=50, null=True, blank=True)
    item1 = models.IntegerField(null=True, blank=True)
    item_description = models.TextField(null=True, blank=True)
    unit_price = models.FloatField(null=True, blank=True)
    amount = models.IntegerField(null=True, blank=True)
    item_contrato = models.ForeignKey(
        Contrato, on_delete=models.CASCADE, null=True, blank=True)
    sum_value = models.FloatField(null=True, blank=True)
    sum_value1 = models.FloatField(null=True, blank=True)
    remove_sum = models.BooleanField(default=False, null=True, blank=True)
    pos_aditivo_value = models.BooleanField(
        default=False, null=True, blank=True)
    identity_aditivo_valor = models.IntegerField(null=True, blank=True)
    pos_supressao = models.BooleanField(
        default=False, null=True, blank=True)
    identity_supressao = models.IntegerField(null=True, blank=True)

    def listar_item():
        return Item.objects.all()

    def listar_item_id(id):
        return Item.objects.filter(item_contrato=id).order_by('item1')

    def listar_item_id_origin(id):
        return Item.objects.filter(item_contrato=id, pos_aditivo_value=False).order_by('item1')

    def valor_contrato(id_contrato):
        return Item.objects.filter(item_contrato=id_contrato, remove_sum=False, pos_aditivo_value=False).aggregate(Sum('sum_value'))['sum_value__sum']

    def total_item_id(id):
        return Item.objects.filter(item_contrato=id).aggregate(Count('item1'))['item1__count']

    def listar_identity_aditivo_valor(id):
        return Item.objects.filter(identity_aditivo_valor=id).order_by('item1')

    def listar_identity_supressao(id):
        return Item.objects.filter(identity_supressao=id).order_by('item1')

    def __str__(self):
        return str(self.item1)


class AditivoPrazo(models.Model):
    contract = models.ForeignKey(
        Contrato, on_delete=models.CASCADE, blank=True, null=True)
    signature_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    validity = models.IntegerField(blank=True, null=True)
    end_validity = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    official_diary = models.CharField(max_length=50, blank=True, null=True)

    def listar_aditivo_prazo_contrato(id):
        return AditivoPrazo.objects.filter(contract=id)

    def aditivo_por_contrato(id):
        return AditivoPrazo.objects.filter(contract=id)

    def __str__(self):
        return str(self.contract)


class AditivoValor(models.Model):
    VALUE_PERCENTAGE = [
        (1, '1%'),
        (2, '2%'),
        (3, '3%'),
        (4, '4%'),
        (5, '5%'),
        (6, '6%'),
        (7, '7%'),
        (8, '8%'),
        (9, '9%'),
        (10, '10%'),
        (11, '11%'),
        (12, '12%'),
        (13, '13%'),
        (14, '14%'),
        (15, '15%'),
        (16, '16%'),
        (17, '17%'),
        (18, '18%'),
        (19, '19%'),
        (20, '20%'),
        (21, '21%'),
        (22, '22%'),
        (23, '23%'),
        (24, '24%'),
        (25, '25%'),

    ]
    contract = models.ForeignKey(
        Contrato, on_delete=models.CASCADE, blank=True, null=True)
    signature_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    validity = models.IntegerField(blank=True, null=True)
    end_validity = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    official_diary = models.CharField(max_length=50, blank=True, null=True)
    percentage = models.FloatField(
        choices=VALUE_PERCENTAGE, blank=True, null=True)
    aditivo_value = models.FloatField(null=True, blank=True)
    difference = models.FloatField(null=True, blank=True)

    def aditivo_value_id(id_aditivo):
        return AditivoValor.objects.get(pk=id_aditivo)

    def aditivo_value_contract(id):
        return AditivoValor.objects.filter(contract=id)

    def valor_percentage_contract(id):
        return AditivoValor.objects.filter(contract=id).aggregate(Sum('percentage'))['percentage__sum']

    def aditivo_value_last():
        return AditivoValor.objects.last()

    def __str__(self):
        return str(self.contract)


class Supressao(models.Model):
    contract = models.ForeignKey(
        Contrato, on_delete=models.CASCADE, blank=True, null=True)
    signature_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    validity = models.IntegerField(blank=True, null=True)
    end_validity = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    official_diary = models.CharField(max_length=50, blank=True, null=True)
    percentage = models.FloatField(blank=True, null=True)
    aditivo_value = models.FloatField(null=True, blank=True)
    difference = models.FloatField(null=True, blank=True)

    def supressao_value_last():
        return Supressao.objects.last()

    def get_supressao(id):
        return Supressao.objects.get(pk=id)

    def aditivo_value_id(id_supressao):
        return Supressao.objects.get(pk=id_supressao)

    def listar_supressao_contract(id):
        return Supressao.objects.filter(contract=id)

    def valor_percentage_contract_sup(id):
        return Supressao.objects.filter(contract=id).aggregate(Sum('percentage'))['percentage__sum']

    def __str__(self):
        return str(self.contract)


class Metafisico(models.Model):
    contract = models.ForeignKey(
        Contrato, on_delete=models.CASCADE, blank=True, null=True)
    signature_date = models.DateField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    validity = models.IntegerField(blank=True, null=True)
    end_validity = models.DateField(
        auto_now=False, auto_now_add=False, null=True, blank=True)
    official_diary = models.CharField(max_length=50, blank=True, null=True)
    percentage = models.FloatField(blank=True, null=True)
    aditivo_value = models.FloatField(null=True, blank=True)
    difference = models.FloatField(null=True, blank=True)

apps/juridico/forms.py
from django.forms import ModelForm
from . models import Contrato, Item, Tipo, AditivoPrazo, AditivoValor, Supressao


class ContratoForm(ModelForm):
    class Meta:
        model = Contrato
        fields = ['company', 'number', 'validity',
                  'signature_date', 'type_contrato', 'official_diary']


class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ['item1', 'item_description',
                  'unit_price', 'amount', 'item_contrato']


class TipoForm(ModelForm):
    class Meta:
        model = Tipo
        fields = ['name', 'description']


class AditivoPrazoForm(ModelForm):
    class Meta:
        model = AditivoPrazo
        fields = ['signature_date', 'validity',
                  'signature_date', 'official_diary']


class AditivoValorForm(ModelForm):
    class Meta:
        model = AditivoValor
        fields = ['signature_date', 'validity', 'official_diary', 'percentage']


class SupressaoForm(ModelForm):
    class Meta:
        model = Supressao
        fields = ['signature_date', 'validity', 'official_diary', 'percentage']

apps/juridico/templates/juridico/dados_contrato.html
{% extends 'plataforma_base_juridico.html' %}



{% block title %}
Juridicoss
{% endblock title %}


{% block content %}
<div id="content" class="app-content">
    <br>
    {% include 'partials/plataforma/_message.html' %}
    <!-- BEGIN card -->
    <div class="card mb-3">
        <!-- BEGIN card-body -->
        <div class="card-body">
            <div class="d-flex mb-3">
                <div class="flex-grow-1">
                    <h5 class="mb-1">Contrato</h5>
                    <div>{{ contrato.company }}</div>
                </div>
                <a href="{% url 'juridico:dados_contrato' contrato.id %}" class="text-muted"><i class="fa fa-redo"></i></a>
            </div>

            <div class="d-flex">
                <div class="flex-grow-1">
                    <h3 class="mb-1">Total de itens: {{ total_item_id }}</h3>
                    <h3 class="mb-1">Valor Total: R$ {{ valor_contrato | floatformat:"2g" }}</h3>

                </div>
                <div
                    class="width-50 height-50 bg-primary-transparent-2 rounded-circle d-flex align-items-center justify-content-center">
                    <i class="fa fa-file-alt fa-lg text-primary"></i>
                </div>
            </div>
        </div>
        <!-- END card-body -->
    </div>
    <!-- END card -->
    <div class="card">
        <div class="card-header"><i class="fa fa-clock"></i></div>
        <div class="card-body">
            <h5 class="card-title">Aditivos de Prazo </h5>
            <h6 class="card-subtitle mb-3 text-muted">Aditivo de Prazo</h6>
            <p class="card-text mb-3">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Data da Assinatura</th>
                            <th scope="col">Vigência</th>
                            <th scope="col">Termino</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>


                        {% for aditivo_por_contrato in aditivo_por_contrato %}
                        <tr>
                            <td>{{ aditivo_por_contrato.signature_date }}</td>
                            <td>{{ aditivo_por_contrato.validity }}</td>
                            <td>{{ aditivo_por_contrato.end_validity }}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="...">

                                    <a href="{% url 'juridico:deletar_aditivo_praso' aditivo_por_contrato.id %}"
                                        class="btn btn-outline-danger"><i class="fa fa-trash-alt"></i></a>
                                </div>
                            </td>

                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
            </p>

        </div>
    </div>
    <hr>
    <div class="card">
        <div class="card-header"><i class="fa fa-money-bill-alt"></i></div>
        <div class="card-body">
            <h5 class="card-title">Aditivos de Valor </h5>
            <h6 class="card-subtitle mb-3 text-muted">Aditivo de Valor</h6>
            <p class="card-text mb-3">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Data da Assinatura</th>
                            <th scope="col">Vigência</th>
                            <th scope="col">Termino</th>
                            <th scope="col">Porcentagem</th>
                            <th scope="col">Valor</th>
                            <th scope="col">Saldo</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>


                        {% for lista_aditivo_valor in lista_aditivo_valor %}
                        <tr>
                            <td class="align-middle">
                                <a href="{% url 'juridico:dados_aditivo_valor' lista_aditivo_valor.contract.id lista_aditivo_valor.id %}"
                                    class="btn btn-outline-default"><i class="fa fa-plus"></i></a>
                            </td>
                            <td>{{ lista_aditivo_valor.signature_date }}</td>
                            <td>{{ lista_aditivo_valor.validity }}</td>
                            <td>{{ lista_aditivo_valor.end_validity }}</td>
                            <td>{{ lista_aditivo_valor.percentage }} %</td>
                            <td>{{ lista_aditivo_valor.aditivo_value | floatformat:"2g" }}</td>
                            <td>{{ lista_aditivo_valor.difference | floatformat:"2g" }}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="...">

                                    <a href="{% url 'juridico:deletar_aditivo_valor' lista_aditivo_valor.id %}" class="btn btn-outline-danger"><i class="fa fa-trash-alt"></i></a>
                                </div>
                            </td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            </p>
        </div>


    </div>

    <hr>
    <div class="card">
        <div class="card-header"><i class="fa fa-money-bill-alt"></i></div>
        <div class="card-body">
            <h5 class="card-title">Supressão </h5>
            <h6 class="card-subtitle mb-3 text-muted">Supressão</h6>
            <p class="card-text mb-3">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Data da Assinatura</th>
                            <th scope="col">Vigência</th>
                            <th scope="col">Termino</th>
                            <th scope="col">Porcentagem</th>
                            <th scope="col">Valor</th>
                            <th scope="col">Saldo</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>


                        {% for listar_supressao_contract in listar_supressao_contract %}
                        <tr>
                            <td class="align-middle">
                                <a href="{% url 'juridico:dados_supressao' listar_supressao_contract.contract.id listar_supressao_contract.id %}"
                                    class="btn btn-outline-default"><i class="fa fa-plus"></i></a>
                            </td>
                            <td>{{ listar_supressao_contract.signature_date }}</td>
                            <td>{{ listar_supressao_contract.validity }}</td>
                            <td>{{ listar_supressao_contract.end_validity }}</td>
                            <td>{{ listar_supressao_contract.percentage }} %</td>
                            <td>{{ listar_supressao_contract.aditivo_value | floatformat:"2g" }}</td>
                            <td>{{ listar_supressao_contract.difference | floatformat:"2g" }}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="...">

                                    <a href="{% url 'juridico:deletar_supressao' listar_supressao_contract.id %}" class="btn btn-outline-danger"><i class="fa fa-trash-alt"></i></a>
                                </div>
                            </td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            </p>
        </div>


    </div>
   
    <hr>
  
    <div class="card">
        <div class="card-header"><i class="fa fa-list"></i></div>
        <div class="card-body">
            <h5 class="card-title">Itens do Contrato </h5>
            <h6 class="card-subtitle mb-3 text-muted">Total de itens do contrato {{ total_item_id }}</h6>
            <p class="card-text mb-3">
            <div class="table-responsive">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Item</th>
                                <th scope="col">Descrição</th>
                                <th scope="col">Preço Unitário</th>
                                <th scope="col">Quantidade</th>
                                <th scope="col">Valor Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for listar_item_id in listar_item_id %}
                            <tr>
                                <th>{{ listar_item_id.item1 }}</th>
                                <td>{{ listar_item_id.item_description }}</td>
                                <td>R$ {{ listar_item_id.unit_price | floatformat:"2g" }}</td>
                                <td>R$ {{ listar_item_id.amount | floatformat:"2g" }}</td>
                                <del></del>
                                <td class="">

                                    {% if listar_item_id.remove_sum == True %}
                                    <span
                                        class="badge bg-danger-transparent-3 text-black-transparent-5 px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center">
                                        <i class="fa fa-circle fs-9px fa-fw me-5px text-danger-transparent-8"></i><del>R$
                                            {{ listar_item_id.sum_value | floatformat:"2g" }} </del>: Excluido
                                    </span>
                                    {% elif listar_item_id.pos_aditivo_value == True %}
                                    <span
                                        class="badge bg-success-transparent-3 text-black-transparent-5 px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center">
                                        <i class="fa fa-circle fs-9px fa-fw me-5px text-success-transparent-8"></i>R$
                                        {{ listar_item_id.sum_value | floatformat:"2g" }} : Aditivo de Valor
                                    </span>
                                    {% elif listar_item_id.pos_supressao == True %}
                                    <span
                                        class="badge bg-danger-transparent-3 text-black-transparent-5 px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center">
                                        <i class="fa fa-circle fs-9px fa-fw me-5px text-danger-transparent-8"></i>R$
                                        {{ listar_item_id.sum_value | floatformat:"2g" }} : Supressão
                                    </span>
                                    {% else %}
                                    {{ listar_item_id.sum_value | floatformat:"2g" }}
                                    {% endif %}

                                </td>
                            </tr>
                            {% empty %}
                            <li>Ainda não foram adcionados itens a esse contrato</li>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            </p>

        </div>
    </div>
   
</div>
{% endblock content %}

apps/juridico/templates/juridico/listar_contratos.html
{% extends 'plataforma_base_juridico.html' %}
{% load filters %}



{% block title %}
Juridico
{% endblock title %}


{% block content %}
<div id="content" class="app-content">
    <div class="d-flex align-items-center mb-3">
        <div>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'juridico:juridico' %}">INÍCIO</a></li>
                <li class="breadcrumb-item active">LISTAR CONTRATOS</li>
            </ul>
            <h1 class="page-header mb-0">Contratos</h1>
        </div>

        <div class="ms-auto">
            <a href="{% url 'juridico:novo_contrato' %}" class="btn btn-outline-primary"><i
                    class="fa fa-plus-circle fa-fw me-1"></i> Novo Contrato</a>
        </div>
    </div>



    <div class="mb-md-4 mb-3 d-md-flex">
        <div class="mt-md-0 mt-2"><a href="#" class="text-dark text-decoration-none"><i
                    class="fa fa-download fa-fw me-1 text-muted"></i> Exportar</a></div>

    </div>
    <div class="card">
        <ul class="nav nav-tabs nav-tabs-v2 px-4">
            <li class="nav-item me-3"><a href="#allTab" class="nav-link active px-2" data-bs-toggle="tab">Todos</a></li>
            <li class="nav-item me-3"><a href="#publishedTab" class="nav-link px-2" data-bs-toggle="tab">Vencidos</a>

        </ul>
        {% include 'partials/plataforma/_message.html' %}
        <div class="tab-content p-4">
            <div class="tab-pane fade show active" id="allTab">
                <!-- BEGIN input-group -->
                <div class="input-group mb-4">



                </div>
                <!-- END input-group -->

                <!-- BEGIN table -->
                <div class="table-responsive">
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th class="border-top-0 pt-0 pb-2"></th>
                                <th class="border-top-0 pt-0 pb-2"></th>
                                <th class="border-top-0 pt-0 pb-2">Data do Cadastro </th>
                                <th class="border-top-0 pt-0 pb-2">Empresa</th>
                                <th class="border-top-0 pt-0 pb-2">Data da Assinatura</th>
                                <th class="border-top-0 pt-0 pb-2">Vigência | Mês</th>
                                <th class="border-top-0 pt-0 pb-2">Termino</th>
                                <th class="border-top-0 pt-0 pb-2">Número</th>
                                <th class="border-top-0 pt-0 pb-2">Diário Ofical</th>
                                <th class="border-top-0 pt-0 pb-2">Tipo</th>
                                <th class="border-top-0 pt-0 pb-2">Responsavel</th>
                                <th class="border-top-0 pt-0 pb-2">Aditivo de Prazo</th>
                                <th class="border-top-0 pt-0 pb-2"></th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for listar_contrato in listar_contratos %}



                            <tr>
                                <td class="width-10 align-middle">
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" id="product1">
                                        <label class="form-check-label" for="product1"></label>
                                    </div>
                                </td>
                                <td class="align-middle">
                                    <a href="{% url 'juridico:dados_contrato' listar_contrato.id %}"
                                        class="btn btn-outline-default"><i class="fa fa-eye"></i></a>
                                </td>
                                <td class="align-middle">{{ listar_contrato.date }}</td>
                                <td class="align-middle">{{ listar_contrato.company }}</td>
                                <td class="align-middle">{{ listar_contrato.signature_date }}</td>
                                <td>{{ listar_contrato.validity }}</td>
                                <td class="py-1 align-middle">{{ listar_contrato.end_validity }}</td>
                                <td class="align-middle">{{ listar_contrato.number }}</td>
                                <td class="align-middle">{{ listar_contrato.official_diary }}</td>
                                <td class="align-middle">{{ listar_contrato.type_contrato.name }}</td>
                                <td class="align-middle">{{ listar_contrato.responsible }}</td>
                                <td class="py-1 align-middle"><span
                                        class="badge bg-gray-100 text-black-transparent-5 px-2 pt-5px pb-5px rounded fs-12px d-inline-flex align-items-center"><i
                                            class="fa fa-circle text-gray-500 fs-9px fa-fw me-5px"></i>
                                        {{ listar_contrato.id | verificar_aditivo_prazo }}</span></td>
                                <td class="align-middle">
                                    <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                        <a href="{% url 'juridico:processos' listar_contrato.id listar_contrato.company %}"
                                            class="btn btn-outline-default"><i class="fa fa-redo"></i></a>
                                    </div>
                                </td>
                            </tr>

                            {% endfor %}

                        </tbody>
                    </table>
                </div>
                <!-- END table -->


            </div>
        </div>
    </div>
</div>
{% endblock content %}

apps/juridico/templates/juridico/tipo_form.html
{% extends 'plataforma_base_juridico.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}
Contratos
{% endblock title %}


{% block content %}
<div id="content" class="app-content">
    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'juridico:juridico' %}">Inicio</a></li>
        <li class="breadcrumb-item active">Cadastro de Tipo</li>
    </ul>
    <div class="card">
        <div class="card-header">Formulário</div>
        <div class="card-body">
            <h5 class="card-title">Formulário</h5>
            <h6 class="card-subtitle mb-3 text-muted">Cadastro de Tipo de Contrato</h6>
            {% include 'partials/plataforma/_message.html' %}
            <p class="card-text mb-3">
            <form action="" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm">
                        <label for="exampleFormControlInput1" class="form-label">Nome:</label>
                        {{ form.name | add_class:"form-control" }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm">
                        <label for="exampleFormControlInput1" class="form-label">Descrição:</label>
                        {{ form.description | add_class:"form-control" }}
                    </div>
                </div>
                <hr>
                <button type="submit" class="btn btn-primary">Salvar</button>
                <hr>
            </form>
            </p>
            
        </div>
    </div>
</div>

{% endblock content %}